### PR TITLE
Make the whole theme work on Vizality

### PR DESCRIPTION
**Pull request by cainy-a**
Vizality has different data attributes to those provided by Powercord and DevilBro, so using the following regex I added required attributes for Vizality.
Expression:
```regex
\[data-user-id="(.{18})"\]:not\(img\)
```
Replace:
```regex
$&,\n[vz-user-id="$1"]:not(img)
```

### CODE REVIEW

**Comment by dav1312** [comment]
Some user IDs seem to also have 17 numbers

**Comment by cainy-a** [comment]
huh ok ill have to change my regex then :thinking:

**Comment by dav1312** [comment]
> huh ok ill have to change my regex then 🤔

`{17,18}` should work i guess

**Comment by cainy-a** [comment]
I guess yeah

**Comment by cainy-a** [comment]
Updated with `\[data-user-id="(.{17,18})"\]:not\(img\)` and `$&,\n[vz-user-id="$1"]:not(img)` and with latest usrbgs

**Comment by cainy-a** [comment]
if its relevant i made an auto patcher script https://gist.github.com/cainy-a/f29ed1dc9e1b348d4f2436fa18e95db9

**Comment by cainy-a** [comment]
`\.root-SR8cQa \[data-user-id="([0-9]{17,18})"\],\n\.userPopout-3XzG_A \[data-user-id="([0-9]{17,18})"\]`

`$&,\n.root-SR8cQa [vz-user-id="$1"],\n.userPopout-3XzG_A [vz-user-id="$1"]`

**Pull request closed without merging**
