### PR TITLE
Add l0c4lh057#9748 to usrbg.json

### PR DESCRIPTION
**Pull request by l0c4lh057**

### CODE REVIEW

**Comment by l0c4lh057** [comment]
> You should expect to **wait a short amount of time**

What exactly is a short amount of time?

**Comment by dav1312** [comment]
> > You should expect to **wait a short amount of time**
> 
> What exactly is a short amount of time?

Yes

**Comment by iamalicecarroll** [comment]
> > You should expect to **wait a short amount of time**
> 
> 
> 
> What exactly is a short amount of time?

Until the PR gets merged

**Comment by l0c4lh057** [comment]
It seems to me like the merge conflicts aren't the problem, as the maintainer said, because I don't see any merge conflict here ¯\\\_(ツ)\_/¯

**Pull request closed without merging**
